# Generated by Django 5.0 on 2023-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('authors', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('institutions', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('pdf_url', models.URLField()),
                ('references', models.TextField()),
            ],
        ),
    ]
