# Generated by Django 5.0.1 on 2024-02-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagementAPP', '0002_userarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserArticle',
        ),
    ]
