# Generated by Django 5.0 on 2024-02-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagementAPP', '0006_alter_article_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_url',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
