# Generated by Django 5.0 on 2024-02-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagementAPP', '0007_alter_article_pdf_url_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='institutions',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True),
        ),
    ]
