# Generated by Django 5.0 on 2023-12-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagementAPP', '0002_userarticle'),
        ('userManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleManagementAPP.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagementApp.user')),
            ],
        ),
    ]
