# Generated by Django 5.0.1 on 2024-02-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagementApp', '0002_favoritearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userManagementApp.user')),
            ],
            bases=('userManagementApp.user',),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
